### ISSUE TITLE
Process Shortcuts or other preference items

### ISSUE THREAD

**Issue by NathanHopkins6283** [mmeierm/ADMX_Templates#1]
Hi,

Can your script be adjusted to process shortcuts, files or other preference items?

Thanks!

**Comment by mmeierm** [comment]
Hi, i'm not aware, if this can be done via ADMX Ingestion, but you can deploy such things using Remediations in Intune:

https://mikemdm.de/2023/05/28/verify-and-replace-files-with-proactive-remediations-in-intune/

Best Regards
Michael
